### ISSUE TITLE
Respect loglevel from IConfiguration

### ISSUE THREAD

**Issue by matthiasharrer** [AXOOM/Axoom.Extensions.Logging.Console#2]
The NLog loglevel can be configured from an appsettings.json or similar like 
```
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Trace"
    },
    "Format": "Gelf"
```

It would be useful if this setting would also be used by this wrapper library when passing the IConfiguration object in.

**Comment by typusomega** [comment]
Are you adding the `ConfigurationSection` in your `AddLogging()` Statement?

```c#
 services.AddLogging(builder => builder.AddConfiguration(Configuration.GetSection("Logging")))
```

**Comment by matthiasharrer** [comment]
This seems to do the trick.. Thanks!
